// app/blogs/content.ts
  export const allBlogs = [
    // Trend Tracker 
    {
      slug: "post1",
      category: "trend_tracker",
      title: "Roof Whisperers: Predicting Problems Before They Pour",
      author: "Bilal S.",
      authorRole: "Founder & CEO - BDR",
      date: "April 1, 2025",
      readTime: "9 min read",
      spotifyUrl: "https://open.spotify.com/episode/7omuwjLR8wtJL7ucoZjzzs?si=ef5a1c6ccb294c70",
      tags: ["Predictive Analytics", "Smart Buildings", "Maintenance"],
      image: "/blogs/trend_tracker/post1/image.png",
      excerpt:
        "How predictive analytics, sensors, and machine learning are transforming commercial roof maintenance from reactive to proactive — saving cost and extending lifespan.",
    },
    {
      slug: "post2",
      category: "trend_tracker",
      title: "Smart Roofing Materials: Transforming the Future of Buildings",
      author: "Bilal S.",
      authorRole: "Founder & CEO - BDR",
      date: "April 29, 2025",
      readTime: "13 min read",
      spotifyUrl: "https://open.spotify.com/show/64ZFIlUZt4SrvRPkeX36wX?si=ec74a20bcca44ac5",
      tags: [ "Smart Materials", "Self-Healing Roofing", "Nanotechnology", "Adaptive Roofing", "Building Innovation"],
      image: "/blogs/trend_tracker/post2/image.png",
      excerpt:
        "Self-healing polymers, adaptive coatings, and nanotech are revolutionizing roofing. Discover how smart materials are making buildings more resilient, efficient, and even self-aware.",
    },
    {
      slug: "post3",
      category: "trend_tracker",
      title: "The Drone Roof Inspection Revolution: Why Drones Are Redefining Building Intelligence",
      author: "Bilal S.",
      authorRole: "Founder & CEO - BDR",
      date: "May 27, 2025",
      readTime: "16 min read",
      spotifyUrl: "https://open.spotify.com/show/64ZFIlUZt4SrvRPkeX36wX?si=ec74a20bcca44ac5",
      tags: ["Drone Inspection", "Building Intelligence", "AI in Roofing", "Thermal Imaging", "Smart Maintenance"],
      image: "/blogs/trend_tracker/post3/image.png",
      excerpt:
        "Drones are transforming roof inspections from risky manual surveys to precise, AI-powered diagnostics. Learn how platforms, sensors, and deep learning are redefining how buildings are assessed and maintained.",
    },
    {
      slug: "post4",
      category: "trend_tracker",
      title: "Rethinking Roofs: Building Climate Resilience from the Top Down",
      author: "Bilal S.",
      authorRole: "Founder & CEO - BDR",
      date: "June 24, 2025",
      readTime: "10 min read",
      spotifyUrl: "https://open.spotify.com/show/64ZFIlUZt4SrvRPkeX36wX?si=ec74a20bcca44ac5",
      tags: [ "Climate Resilience", "Roofing Strategy", "Building Codes", "Green Roofs", "Energy Modeling"],
      image: "/blogs/trend_tracker/post4/image.png",
      excerpt:
        "Roofs are no longer just building tops—they’re climate shields. This deep dive explores how data-driven models, resilient materials, and evolving codes are transforming roofing into the first line of defense in a warming world.",
    },
    // Project Profiles
    {
      slug: "post1",
      category: "project_profiles",
      title: "Behind the Walls: Battling Hidden Water Intrusion",
      author: "Bilal S.",
      authorRole: "Founder & CEO - BDR",
      date: "April 8, 2025",
      readTime: "10 min read",
      spotifyUrl: "https://open.spotify.com/episode/09KWa0RVHJveOzRoFHJNPY?si=d81b4490a90c4a1e",
      tags: ["Water Intrusion", "Forensic Testing", "NDT", "Moisture Detection", "Building Envelopes"],
      image: "/blogs/project_profiles/post1/image.png",
      excerpt: "Behind-the-scenes water damage can silently destroy buildings. This case study explores modern tools and forensic protocols to locate, understand, and prevent hidden water intrusion.",
    },
    {
      slug: "post2",
      category: "project_profiles",
      title: "Raising the Roof: Secrets to Making Your Roof Last Decades Longer",
      author: "Bilal S.",
      authorRole: "Founder & CEO - BDR",
      date: "May 6, 2025",
      readTime: "8 min read",
      spotifyUrl: "https://open.spotify.com/episode/0YUmMvTT54TAbRTfut491a?si=b3a71cbd3b754294",
      tags: ["Roof Longevity", "Maintenance Strategy", "Building Owners", "Lifecycle Planning"],
      image: "/blogs/project_profiles/post2/image.png",
      excerpt: "Explore real-world lessons from buildings that pushed roof life well beyond industry expectations. Learn the key strategies that turn 20-year roofs into 30-year performers without luck or wishful thinking.",
    },
    {
      slug: "post3",
      category: "project_profiles",
      title: "Solving Recurring Ponding on Roofs: What Actually Works",
      author: "Bilal S.",
      authorRole: "Founder & CEO - BDR",
      date: "June 3, 2025",
      readTime: "8 min read",
      spotifyUrl: "https://open.spotify.com/show/64ZFIlUZt4SrvRPkeX36wX?si=ec74a20bcca44ac5",
      tags: ["Ponding", "Roof Drainage", "Tapered Insulation", "Structural Framing", "Roofing Maintenance"],
      image: "/blogs/project_profiles/post3/image.png",
      excerpt:
        "A tactical guide to eliminating roof ponding—covering slope engineering, drainage, tapered insulation, structural framing, and smart maintenance. Learn how to fix the root cause, not the symptoms.",
    },
    {
      slug: "post4",
      category: "project_profiles",
      title: "Emergency Response: Thinking in Systems, Not Just Checklists",
      author: "Bilal S.",
      authorRole: "Founder & CEO - BDR",
      date: "July 1, 2025",
      readTime: "7 min read",
      spotifyUrl: "https://open.spotify.com/show/64ZFIlUZt4SrvRPkeX36wX?si=ec74a20bcca44ac5",
      tags: ["Emergency Planning", "Disaster Response", "System Thinking", "Roofing Failures", "Building Resilience"],
      image: "/blogs/project_profiles/post4/image.png",
      excerpt:
        "Why most emergency response plans fail—and how to build system-level strategies that actually work. Move beyond checklists and into resilient roofing operations.",
    },
    // Owner's Edge
    {
      slug: "post1",
      category: "owners_edge",
      title: "The Hidden Cost Bomb: Why Deferred Maintenance Isn't Saving You Money",
      author: "Bilal S.",
      authorRole: "Founder & CEO - BDR",
      date: "April 15, 2025",
      readTime: "8 min read",
      spotifyUrl: "https://open.spotify.com/episode/3HtFEM2oIptMY9rU7jrzVg?si=cd1f97175aae4572",
      tags: ["Deferred Maintenance", "Lifecycle Costing", "Roofing ROI", "Building Owners"],
      image: "/blogs/owners_edge/post1/image.png",
      excerpt: "Delaying routine maintenance seems like a cost-saving move—until it isn't. This post unpacks the true cost of deferral, from ballooning repair bills to catastrophic business interruption.",
    },
    {
      slug: "post2",
      category: "owners_edge",
      title: "Think Before You Tear Off: Five Non-Negotiable Questions Before Replacing Your Commercial Roof",
      author: "Bilal S.",
      authorRole: "Founder & CEO - BDR",
      date: "May 13, 2025",
      readTime: "8 min read",
      spotifyUrl: "https://open.spotify.com/show/64ZFIlUZt4SrvRPkeX36wX?si=ec74a20bcca44ac5",
      tags: ["Commercial Roofing", "Roof Replacement", "Facility Management", "Maintenance Planning"],
      image: "/blogs/owners_edge/post2/image.png",
      excerpt: "Before replacing your commercial roof, ask these five strategic questions to avoid unnecessary costs, risk exposure, and premature failures.",
    },
    {
      slug: "post3",
      category: "owners_edge",
      title: "Understanding Your Roof Warranty: Cutting Through the Fine Print Like a Pro",
      author: "Bilal S.",
      authorRole: "Founder & CEO - BDR",
      date: "June 10, 2025",
      readTime: "10 min read",
      spotifyUrl: "https://open.spotify.com/show/64ZFIlUZt4SrvRPkeX36wX?si=ec74a20bcca44ac5",
      tags: ["Roof Warranties", "Commercial Roofing", "Maintenance", "Risk Management"],
      image: "/blogs/owners_edge/post3/image.png",
      excerpt: "Roof warranties aren't just paperwork—they’re legal frameworks filled with fine print that can either protect you or leave you hanging. Learn how to navigate the options, spot exclusions, and keep your warranty valid before you need it most.",
    },
    {
      slug: "post4",
      category: "owners_edge",
      title: "The Building Owner’s Guide to Roof Inspections: Build Discipline, Not Disaster",
      author: "Bilal S.",
      authorRole: "Founder & CEO - BDR",
      date: "July 8, 2025",
      readTime: "11 min read",
      spotifyUrl: "https://open.spotify.com/show/64ZFIlUZt4SrvRPkeX36wX?si=ec74a20bcca44ac5",
      tags: ["Roof Inspections", "Preventive Maintenance", "Commercial Roofing", "Asset Management"],
      image: "/blogs/owners_edge/post4/image.png",
      excerpt: "Stop managing your roof by accident. Discover how disciplined, routine inspections protect your building, boost ROI, and turn you into the kind of owner who never gets blindsided by leaks, claims, or costly emergencies.",
    },
    // Tech Talk
    {
      slug: "post1",
      category: "tech_talk",
      title: "Roof Longevity Secrets: Why Some Roofs Thrive and Others Barely Survive",
      author: "Bilal S.",
      authorRole: "Founder & CEO - BDR",
      date: "April 22, 2025",
      readTime: "9 min read",
      spotifyUrl: "https://open.spotify.com/episode/3BDpaaK4i6rKF6oVz4Mk3U?si=f44434ccbd6243ce",
      tags: ["TPO", "EPDM", "Roofing Science", "Membrane Chemistry", "UV Degradation"],
      image: "/blogs/tech_talk/post1/image.png",
      excerpt: "Explore how TPO and EPDM membranes age under real-world conditions, what drives degradation, and how chemistry and installation techniques determine long-term durability.",
    },
    {
      slug: "post2",
      category: "tech_talk",
      title: "Vapor Drive Simplified: How Moisture Moves and Why the Details Matter",
      author: "Bilal S.",
      authorRole: "Founder & CEO - BDR",
      date: "May 20, 2025",
      readTime: "8 min read",
      spotifyUrl: "https://open.spotify.com/show/64ZFIlUZt4SrvRPkeX36wX?si=ec74a20bcca44ac5",
      tags: ["Vapor Drive", "Building Science", "Moisture Control", "Perm Ratings", "Wall Assemblies"],
      image: "/blogs/tech_talk/post2/image.png",
      excerpt:
        "Most people treat vapor drive as a line item. In reality, it’s the hidden force behind mold, decay, and wall failure. Learn how to predict and control it using physics, climate data, and smarter assemblies.",
    },
    {
      slug: "post3",
      category: "tech_talk",
      title: "The Real Game of Wind Uplift Resistance in Roofing Systems",
      author: "Bilal S.",
      authorRole: "Founder & CEO - BDR",
      date: "June 17, 2025",
      readTime: "10 min read",
      spotifyUrl: "https://open.spotify.com/show/64ZFIlUZt4SrvRPkeX36wX?si=ec74a20bcca44ac5",
      tags: ["Wind Uplift", "Roofing Systems", "Fasteners", "FM Standards", "Structural Integrity"],
      image: "/blogs/tech_talk/post3/image.png",
      excerpt:
        "Wind uplift resistance is where theory meets the storm. Learn how standards, fasteners, substrates, and building conditions determine whether your roof holds or fails under real wind pressure.",
    },
    {
      slug: "post4",
      category: "tech_talk",
      title: "The Invisible Leaks: Mastering Thermal Bridging with Precision",
      author: "Bilal S.",
      authorRole: "Founder & CEO - BDR",
      date: "July 15, 2025",
      readTime: "10 min read",
      spotifyUrl: "https://open.spotify.com/show/64ZFIlUZt4SrvRPkeX36wX?si=ec74a20bcca44ac5",
      tags: ["Thermal Bridging", "Energy Efficiency", "Infrared Thermography", "Building Science", "Roofing"],
      image: "/blogs/tech_talk/post4/image.png",
      excerpt:
        "Thermal bridging quietly sabotages building efficiency. Learn how to spot it with thermal imaging, fix it with smart design, and model your way to airtight, energy-smart buildings.",
    },

  ]